In [19]:
import numpy as np

# TO - DO - Task

## Exercise on Functions:

In [162]:
def convert_length(value, conversion_type):
    if conversion_type == 'm_to_ft':
        return value * 3.28084  # Meters to feet
    elif conversion_type == 'ft_to_m':
        return value / 3.28084  # Feet to meters
    else:
        raise ValueError("Unsupported conversion type for length.")

def convert_weight(value, conversion_type):
    if conversion_type == 'kg_to_lb':
        return value * 2.20462  # Kilograms to pounds
    elif conversion_type == 'lb_to_kg':
        return value / 2.20462  # Pounds to kilograms
    else:
        raise ValueError("Unsupported conversion type for weight.")

def convert_volume(value, conversion_type):
    if conversion_type == 'l_to_gal':
        return value * 0.264172  # Liters to gallons
    elif conversion_type == 'gal_to_l':
        return value / 0.264172  # Gallons to liters
    else:
        raise ValueError("Unsupported conversion type for volume.")

def main():
    print("Select the type of conversion:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        conversion_choice = int(input("Enter your choice (1, 2, or 3): "))
        if conversion_choice not in [1, 2, 3]:
            raise ValueError("Invalid choice.")
        
        value = float(input("Enter the value to be converted: "))
        
        if conversion_choice == 1:
            print("Select conversion type:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            length_choice = int(input("Enter your choice (1 or 2): "))
            if length_choice == 1:
                result = convert_length(value, 'm_to_ft')
                print(f"{value} meters is equal to {result:.2f} feet.")
            elif length_choice == 2:
                result = convert_length(value, 'ft_to_m')
                print(f"{value} feet is equal to {result:.2f} meters.")
            else:
                raise ValueError("Invalid length conversion choice.")
        
        elif conversion_choice == 2:
            print("Select conversion type:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            weight_choice = int(input("Enter your choice (1 or 2): "))
            if weight_choice == 1:
                result = convert_weight(value, 'kg_to_lb')
                print(f"{value} kilograms is equal to {result:.2f} pounds.")
            elif weight_choice == 2:
                result = convert_weight(value, 'lb_to_kg')
                print(f"{value} pounds is equal to {result:.2f} kilograms.")
            else:
                raise ValueError("Invalid weight conversion choice.")
        
        elif conversion_choice == 3:
            print("Select conversion type:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            volume_choice = int(input("Enter your choice (1 or 2): "))
            if volume_choice == 1:
                result = convert_volume(value, 'l_to_gal')
                print(f"{value} liters is equal to {result:.2f} gallons.")
            elif volume_choice == 2:
                result = convert_volume(value, 'gal_to_l')
                print(f"{value} gallons is equal to {result:.2f} liters.")
            else:
                raise ValueError("Invalid volume conversion choice.")
        
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()


Select the type of conversion:
1. Length
2. Weight
3. Volume


Enter your choice (1, 2, or 3):  1
Enter the value to be converted:  45


Select conversion type:
1. Meters to Feet
2. Feet to Meters


Enter your choice (1 or 2):  2


45.0 feet is equal to 13.72 meters.


# To - Do - NumPy

## Problem - 1: Array Creation:

In [2]:
# Question 1
array = np.empty((2, 2))
print(array)

[[0. 0.]
 [0. 0.]]


In [4]:
# Question 2
array = np.ones((4, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# Question 3
array = np.full((3,3), 10)
print(array)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [13]:
# Question 4
array = np.zeros_like(array)
print(array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
# Question 5
array = np.ones_like(array)
print(array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
# Question 6
existing_list = [1,2,3,4]
np_existing_arr = np.array(existing_list)
print(np_existing_arr)

[1 2 3 4]


## Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [22]:
# Question 1
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [33]:
# Question 2
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
# Question 3
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
# Question 4
random_array = np.random.random(30).mean()
print(random_array)

0.5304907457951974


In [57]:
# Question 5
max, min = np.random.random(10*10).reshape(10,10).max(), np.random.random(10*10).reshape(10,10).min()
print(f"{max} is the max value\n{min} is the minimum value")

0.9992721032747913 is the max value
0.00518773122158378 is the minimum value


In [76]:
# Question 6
zeros_arr = np.zeros((10,10))
zeros_arr[4] = 1
print(zeros_arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [71]:
# Question 7
arr = [1,2,0,0,4,0]
reveresed_arr = arr[::-1]
print(reveresed_arr)

[0, 4, 0, 0, 2, 1]


In [82]:
# Question 8
sq_matrix = np.ones((4,4))
# '1' → Start from index 1 (skip the first row/column).
# '-1' → Stop before the last index (skip the last row/column).
sq_matrix[1:-1,1:-1] = 0
print(sq_matrix)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [91]:
# Question 9
checkerboard = np.zeros((8, 8), dtype=int)
# '1 Starting Index'::'2 Skip'
checkerboard[1::2, 0::2] = 1
checkerboard[0::2, 1::2] = 1  # Set 1s in alternate rows & cols
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Problem - 3: Array Operations:

In [93]:
# Array Declarations
x = np.array([[1,2],[3,5]]) 
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

In [94]:
# Question 1
added_array = x + y
print(added_array)

[[ 6  8]
 [10 13]]


In [95]:
# Question 2
substracted_array = v - w
print(substracted_array)

[-2 -2]


In [96]:
# Question 3
multiplied_array = 2 * x
print(multiplied_array)

[[ 2  4]
 [ 6 10]]


In [97]:
# Question 4
squarred_array = np.square(x)
print(squarred_array)

[[ 1  4]
 [ 9 25]]


In [112]:
# Question 5
v_w_dot_product = np.dot(v,w)
print(f"V . W : {v_w_dot_product}")

x_v_dot_product = np.dot(x,v)
print(f"X . V : {x_v_dot_product}")

x_y_dot_product = np.dot(x,y)
print(f"X . Y : {x_y_dot_product}")

V . W : 219
X . V : [29 77]
X . Y : [[19 22]
 [50 58]]


In [134]:
# Question 6
print(np.concatenate((x,y)))
print(np.vstack((v,w)))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [138]:
# Question 7
print(np.concatenate((x,v)))


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

It gives an error as the dimension does not match

## Problem - 4: Matrix Operations:

In [140]:
# Array Declarations
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);

In [145]:
# Question 1

# Prove A.A−1 = I.

# Taking out the inverse of the matrix A
A_inverse = np.linalg.inv(A)

# Taking outo the dot product of two matrices
result = np.dot(A, A_inverse)

# Creating an identity matrix of 2x2
I = np.eye(2)

print(np.allclose(result, I))


True


In [151]:
# Question 2

# Prove AB ̸= BA.

# Taking outo the dot product of two matrices
result_ab = np.dot(A, B)
result_ba = np.dot(B, A)

print(result_ab)
print()
print(result_ba)

[[23 13]
 [51 29]]

[[36 44]
 [13 16]]


In [152]:
# Question 3

# Prove (AB)T = BTAT
ab_t = np.transpose(result_ab)
btat = np.dot(np.transpose(B), np.transpose(A))

print(np.allclose(ab_t, btat))

True


In [158]:
# Question 4

# Writing in matrix form
a = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

# Writing the target variable values
b = np.array([-1, -3, 9])

# Taking out the inverse of a
a_inv = np.linalg.inv(a)

# Solving the equation using the inversion method
X = np.dot(a_inv, b)

print("[x, y, z] =" , X)


[x, y, z] = [ 2.  1. -2.]
